set -g prefix C-d

unbind r
bind r source-file ~/.tmux.conf


bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g mouse on
set-option -g status-position top
set -g default-terminal "tmux-256color"

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# C-d I to load plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

run "~/.tmux/plugins/tpm/tpm"
