set -g prefix C-d

unbind r
bind r source-file ~/.tmux.conf


bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key z kill-pane
bind-key x kill-window

unbind '"'
unbind %
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g mouse on
set-option -g status-position top
set -g status 2
set -g 'status-format[1]' ''

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm*:Tc"

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# C-d I to load plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_date_time}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g @catppuccin_date_time_text " %H:%M"

set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'o'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'


run "~/.tmux/plugins/tpm/tpm"

set -g status-style "bg=default"
